<a href="https://colab.research.google.com/github/mirckrose/machinelearning-week2/blob/main/SKLearn_Linear_Models.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##1.1.1. Ordinary Least Squares


In [2]:
from sklearn import linear_model
reg = linear_model.LinearRegression()
reg.fit([[0, 0], [1, 1], [2, 2]], [0, 1, 2])

reg.coef_

array([0.5, 0.5])

#1.1.2. Ridge regression and classification


##1.1.2.1. Regression


In [3]:
from sklearn import linear_model
reg = linear_model.Ridge(alpha=.5)
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])

reg.coef_

reg.intercept_


0.13636363636363638

##1.1.2.4. Setting the regularization parameter: leave-one-out Cross-Validation


In [4]:
import numpy as np
from sklearn import linear_model
reg = linear_model.RidgeCV(alphas=np.logspace(-6, 6, 13))
reg.fit([[0, 0], [0, 0], [1, 1]], [0, .1, 1])


reg.alpha_

0.01

#1.1.3. Lasso


In [5]:
from sklearn import linear_model
reg = linear_model.Lasso(alpha=0.1)

In [6]:
reg.fit([[0, 0], [1, 1]], [0, 1])


Lasso(alpha=0.1)

In [7]:
reg.predict([[1, 1]])


array([0.8])

#1.1.8. LARS Lasso


In [8]:
from sklearn import linear_model
reg = linear_model.LassoLars(alpha=.1, normalize=False)

In [9]:
reg.fit([[0, 0], [1, 1]], [0, 1])


LassoLars(alpha=0.1, normalize=False)

In [10]:
reg.coef_


array([0.6, 0. ])

#1.1.10.1. Bayesian Ridge Regression


In [11]:
from sklearn import linear_model
X = [[0., 0.], [1., 1.], [2., 2.], [3., 3.]]
Y = [0., 1., 2., 3.]
reg = linear_model.BayesianRidge()
reg.fit(X, Y)


BayesianRidge()

In [12]:
reg.predict([[1, 0.]])


array([0.50000013])

In [13]:
reg.coef_


array([0.49999993, 0.49999993])

#1.1.12.1. Usage


In [14]:
from sklearn.linear_model import TweedieRegressor
reg = TweedieRegressor(power=1, alpha=0.5, link='log')
reg.fit([[0, 0], [0, 1], [2, 2]], [0, 1, 2])

TweedieRegressor(alpha=0.5, link='log', power=1)

In [15]:
reg.coef_


array([0.24631611, 0.43370317])

In [16]:
reg.intercept_


-0.7638091359123445

In [16]:
pip uninstall sklearn

Found existing installation: sklearn 0.0
Uninstalling sklearn-0.0:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/sklearn-0.0.dist-info/*
Proceed (y/n)? y
  Successfully uninstalled sklearn-0.0


In [17]:
pip uninstall scikit-learn

Found existing installation: scikit-learn 0.22.2.post1
Uninstalling scikit-learn-0.22.2.post1:
  Would remove:
    /usr/local/lib/python3.7/dist-packages/scikit_learn-0.22.2.post1.dist-info/*
    /usr/local/lib/python3.7/dist-packages/sklearn/*
Proceed (y/n)? y
  Successfully uninstalled scikit-learn-0.22.2.post1


In [18]:
pip install sklearn

     |████████████████████████████████| 23.1 MB 2.9 MB/s 
  Created wheel for sklearn: filename=sklearn-0.0-py2.py3-none-any.whl size=1309 sha256=7b26c004a121bae87abdc7ae6d90355149323dcce50cb435ffe953a596df0492
  Stored in directory: /root/.cache/pip/wheels/46/ef/c3/157e41f5ee1372d1be90b09f74f82b10e391eaacca8f22d33e
Successfully built sklearn


In [1]:
pip install scikit-learn

#1.1.18. Polynomial regression: extending linear models with basis functions


In [17]:
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X = np.arange(6).reshape(3, 2)
X

array([[0, 1],
       [2, 3],
       [4, 5]])

In [18]:
poly = PolynomialFeatures(degree=2)
poly.fit_transform(X)


array([[ 1.,  0.,  1.,  0.,  0.,  1.],
       [ 1.,  2.,  3.,  4.,  6.,  9.],
       [ 1.,  4.,  5., 16., 20., 25.]])

In [19]:
from sklearn.preprocessing import PolynomialFeatures
from sklearn.linear_model import LinearRegression
from sklearn.pipeline import Pipeline
import numpy as np
model = Pipeline([('poly', PolynomialFeatures(degree=3)),
                  ('linear', LinearRegression(fit_intercept=False))])
# fit to an order-3 polynomial data
x = np.arange(5)
y = 3 - 2 * x + x ** 2 - x ** 3
model = model.fit(x[:, np.newaxis], y)
model.named_steps['linear'].coef_


array([ 3., -2.,  1., -1.])

In [20]:
from sklearn.linear_model import Perceptron
from sklearn.preprocessing import PolynomialFeatures
import numpy as np
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])
y = X[:, 0] ^ X[:, 1]
y

array([0, 1, 1, 0])

In [21]:
X = PolynomialFeatures(interaction_only=True).fit_transform(X).astype(int)
X

array([[1, 0, 0, 0],
       [1, 0, 1, 0],
       [1, 1, 0, 0],
       [1, 1, 1, 1]])

In [22]:
clf = Perceptron(fit_intercept=False, max_iter=10, tol=None,
                 shuffle=False).fit(X, y)

In [23]:
clf.predict(X)

array([0, 1, 1, 0])

In [24]:
clf.score(X, y)


1.0